# Generated by Django 4.1 on 2022-08-16 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post/')),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2022, 8, 16, 21, 19, 44, 709074, tzinfo=datetime.timezone.utc))),
                ('content', models.TextField(max_length=5000)),
            ],
        ),
    ]
