# Generated by Django 4.1 on 2022-08-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='about/')),
                ('subtitle', models.TextField(max_length=500)),
                ('aboutme', models.TextField(max_length=2000)),
                ('tw_link', models.URLField()),
                ('lk_link', models.URLField()),
                ('github_link', models.URLField()),
            ],
        ),
    ]
